-- Seed data for LMS (execute after running configurar.py)
BEGIN;
-- Asignaturas
INSERT OR IGNORE INTO asignaturas (nombre, descripcion) VALUES ('Programación', 'Fundamentos de programación');
INSERT OR IGNORE INTO asignaturas (nombre, descripcion) VALUES ('Bases de datos', 'Modelado y SQL');
INSERT OR IGNORE INTO asignaturas (nombre, descripcion) VALUES ('Lenguajes de marcas', 'HTML/CSS/JS/XML');
INSERT OR IGNORE INTO asignaturas (nombre, descripcion) VALUES ('Entornos de desarrollo', 'Herramientas y metodologías');
INSERT OR IGNORE INTO asignaturas (nombre, descripcion) VALUES ('Sistemas Informáticos', 'SO y redes');
INSERT OR IGNORE INTO asignaturas (nombre, descripcion) VALUES ('FOL', 'Formación y orientación laboral');
INSERT OR IGNORE INTO asignaturas (nombre, descripcion) VALUES ('Despliegue de aplicaciones', 'DevOps básico');
INSERT OR IGNORE INTO asignaturas (nombre, descripcion) VALUES ('Seguridad', 'Buenas prácticas y auditoría');
INSERT OR IGNORE INTO asignaturas (nombre, descripcion) VALUES ('Inglés Técnico', 'Inglés aplicado a IT');
INSERT OR IGNORE INTO asignaturas (nombre, descripcion) VALUES ('Acceso a datos', 'DAO, ORM');
INSERT OR IGNORE INTO asignaturas (nombre, descripcion) VALUES ('Desarrollo interfaces', 'UI/UX en escritorio');
INSERT OR IGNORE INTO asignaturas (nombre, descripcion) VALUES ('Empresa e iniciativa', 'Emprendimiento');
-- Cursos
INSERT OR IGNORE INTO cursos (nombre, descripcion) VALUES ('DAM 1º', 'Grupo DAM 1º');
INSERT OR IGNORE INTO cursos (nombre, descripcion) VALUES ('DAM 2º', 'Grupo DAM 2º');
INSERT OR IGNORE INTO cursos (nombre, descripcion) VALUES ('DAW 1º', 'Grupo DAW 1º');
INSERT OR IGNORE INTO cursos (nombre, descripcion) VALUES ('DAW 2º', 'Grupo DAW 2º');
INSERT OR IGNORE INTO cursos (nombre, descripcion) VALUES ('ASIR 1º', 'Grupo ASIR 1º');
INSERT OR IGNORE INTO cursos (nombre, descripcion) VALUES ('ASIR 2º', 'Grupo ASIR 2º');
INSERT OR IGNORE INTO cursos (nombre, descripcion) VALUES ('SMR 1º', 'Grupo SMR 1º');
INSERT OR IGNORE INTO cursos (nombre, descripcion) VALUES ('SMR 2º', 'Grupo SMR 2º');
INSERT OR IGNORE INTO cursos (nombre, descripcion) VALUES ('IA Básica', 'Grupo IA Básica');
INSERT OR IGNORE INTO cursos (nombre, descripcion) VALUES ('Full‑stack Web', 'Grupo Full‑stack Web');
-- Profesores
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Nuria', 'Díaz', 'nuria.díaz@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Carmen', 'Cano', 'carmen.cano@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Lucía', 'Pérez', 'lucía.pérez@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Isabel', 'Martín', 'isabel.martín@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Alicia', 'Cortés', 'alicia.cortés@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Lucía', 'Marín', 'lucía.marín@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Paula', 'López', 'paula.lópez@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Elena', 'Ortega', 'elena.ortega@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Iván', 'Pérez', 'iván.pérez@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Noa', 'Gómez', 'noa.gómez@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Alberto', 'Ortega', 'alberto.ortega@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Lucía', 'Cabrera', 'lucía.cabrera@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Sara', 'Ruiz', 'sara.ruiz@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Adrián', 'Guerrero', 'adrián.guerrero@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Bruno', 'Cortés', 'bruno.cortés@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Lucía', 'Garrido', 'lucía.garrido@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Óscar', 'Molina', 'óscar.molina@prof.centro.edu');
INSERT INTO profesores (nombre, apellidos, email) VALUES ('Lucía', 'Alonso', 'lucía.alonso@prof.centro.edu');
-- Alumnos
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Juan', 'Medina', 'juan.medina@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Diego', 'Domínguez', 'diego.domínguez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Iván', 'Díaz', 'iván.díaz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Isabel', 'Ruiz', 'isabel.ruiz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Sara', 'Vázquez', 'sara.vázquez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Alberto', 'Cabrera', 'alberto.cabrera@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Inés', 'Álvarez', 'inés.álvarez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Pablo', 'Cortés', 'pablo.cortés@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Sara', 'Guerrero', 'sara.guerrero@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Sergio', 'Serrano', 'sergio.serrano@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Pablo', 'Medina', 'pablo.medina@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Rocío', 'Pérez', 'rocío.pérez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Sara', 'Sánchez', 'sara.sánchez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Teresa', 'Romero', 'teresa.romero@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Clara', 'Méndez', 'clara.méndez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Isabel', 'Ortega', 'isabel.ortega@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Ariadna', 'Ramos', 'ariadna.ramos@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Raquel', 'Cortés', 'raquel.cortés@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Raquel', 'Serrano', 'raquel.serrano@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Daniel', 'Gutiérrez', 'daniel.gutiérrez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Ana', 'Cruz', 'ana.cruz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Ariadna', 'Gutiérrez', 'ariadna.gutiérrez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Elena', 'Garrido', 'elena.garrido@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Daniel', 'Sanz', 'daniel.sanz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Clara', 'Gil', 'clara.gil@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Guillermo', 'Delgado', 'guillermo.delgado@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Irene', 'Castillo', 'irene.castillo@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Carlos', 'Ruiz', 'carlos.ruiz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Andrés', 'Suárez', 'andrés.suárez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Marco', 'León', 'marco.león@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('David', 'Díaz', 'david.díaz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Clara', 'Suárez', 'clara.suárez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Juan', 'Prieto', 'juan.prieto@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Carlos', 'León', 'carlos.león@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Alberto', 'Garrido', 'alberto.garrido@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Nuria', 'Gil', 'nuria.gil@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Álvaro', 'Ramírez', 'álvaro.ramírez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Beatriz', 'Rubio', 'beatriz.rubio@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Óscar', 'Flores', 'óscar.flores@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Raquel', 'Pérez', 'raquel.pérez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Elena', 'Torres', 'elena.torres@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Rubén', 'Cruz', 'rubén.cruz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Borja', 'Pérez', 'borja.pérez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Lucía', 'Gallego', 'lucía.gallego@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Álvaro', 'Vázquez', 'álvaro.vázquez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Nerea', 'Garrido', 'nerea.garrido@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Inés', 'Cabrera', 'inés.cabrera@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Gonzalo', 'Domínguez', 'gonzalo.domínguez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Rocío', 'Blanco', 'rocío.blanco@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Borja', 'Ramírez', 'borja.ramírez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('María', 'Castro', 'maría.castro@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Marta', 'Moreno', 'marta.moreno@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Teresa', 'Ruiz', 'teresa.ruiz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Clara', 'Sánchez', 'clara.sánchez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Paula', 'Herrera', 'paula.herrera@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Irene', 'Hernández', 'irene.hernández@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Lola', 'Gutiérrez', 'lola.gutiérrez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Carmen', 'Molina', 'carmen.molina@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Clara', 'Gómez', 'clara.gómez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Marco', 'Delgado', 'marco.delgado@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Carmen', 'Medina', 'carmen.medina@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Vega', 'Hernández', 'vega.hernández@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Laura', 'Medina', 'laura.medina@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Vega', 'Calvo', 'vega.calvo@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Iván', 'Ramírez', 'iván.ramírez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Inés', 'Blanco', 'inés.blanco@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Adrián', 'Díaz', 'adrián.díaz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Elena', 'Álvarez', 'elena.álvarez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Julia', 'Alonso', 'julia.alonso@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Borja', 'Alonso', 'borja.alonso@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Alex', 'Rubio', 'alex.rubio@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Óscar', 'Álvarez', 'óscar.álvarez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Hugo', 'Domínguez', 'hugo.domínguez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Alex', 'Díaz', 'alex.díaz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Iván', 'Iglesias', 'iván.iglesias@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Alicia', 'Santos', 'alicia.santos@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Sara', 'Ramos', 'sara.ramos@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Diego', 'Cruz', 'diego.cruz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Andrés', 'Santos', 'andrés.santos@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Nerea', 'Méndez', 'nerea.méndez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Lola', 'Sánchez', 'lola.sánchez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Raquel', 'Herrera', 'raquel.herrera@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Inés', 'Flores', 'inés.flores@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Alberto', 'Molina', 'alberto.molina@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Carmen', 'Molina', 'carmen.molina@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Carmen', 'Martín', 'carmen.martín@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Rubén', 'Guerrero', 'rubén.guerrero@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Carmen', 'Sánchez', 'carmen.sánchez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Sergio', 'Pérez', 'sergio.pérez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Paula', 'Delgado', 'paula.delgado@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Marco', 'Ruiz', 'marco.ruiz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('David', 'Castillo', 'david.castillo@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Lucía', 'Martín', 'lucía.martín@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Alex', 'Garrido', 'alex.garrido@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Julia', 'Iglesias', 'julia.iglesias@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Pablo', 'Serrano', 'pablo.serrano@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Teresa', 'Martínez', 'teresa.martínez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Carlos', 'Romero', 'carlos.romero@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Teresa', 'Blanco', 'teresa.blanco@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Julia', 'Guerrero', 'julia.guerrero@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Hugo', 'Ramírez', 'hugo.ramírez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Beatriz', 'Serrano', 'beatriz.serrano@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Rubén', 'Ruiz', 'rubén.ruiz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Sofía', 'Rubio', 'sofía.rubio@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Raquel', 'Ortiz', 'raquel.ortiz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Rubén', 'Vázquez', 'rubén.vázquez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Elena', 'Díaz', 'elena.díaz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Pablo', 'Vidal', 'pablo.vidal@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('David', 'Vidal', 'david.vidal@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Hugo', 'Ortiz', 'hugo.ortiz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Álvaro', 'Moreno', 'álvaro.moreno@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Nicolás', 'Martínez', 'nicolás.martínez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Paula', 'Sanz', 'paula.sanz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Alicia', 'Díaz', 'alicia.díaz@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Álvaro', 'Iglesias', 'álvaro.iglesias@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('María', 'León', 'maría.león@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Nicolás', 'Vázquez', 'nicolás.vázquez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Nerea', 'Gómez', 'nerea.gómez@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Álvaro', 'Navarro', 'álvaro.navarro@alu.centro.edu');
INSERT INTO alumnos (nombre, apellidos, email) VALUES ('Nicolás', 'Serrano', 'nicolás.serrano@alu.centro.edu');
-- Cursos ↔ Asignaturas
DELETE FROM cursos_asignaturas;
DELETE FROM imparticiones;
DELETE FROM matriculas;
DELETE FROM materiales;
-- Above deletes are safe for demo to re-seed relations and materials.
-- Build course-subject relations
WITH c AS (SELECT id FROM cursos), a AS (SELECT id FROM asignaturas) SELECT 1; -- placeholder (SQLite ignores)
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAM 1º'), (SELECT id FROM asignaturas WHERE nombre='Lenguajes de marcas'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAM 1º'), (SELECT id FROM asignaturas WHERE nombre='FOL'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAM 1º'), (SELECT id FROM asignaturas WHERE nombre='Entornos de desarrollo'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAM 1º'), (SELECT id FROM asignaturas WHERE nombre='Inglés Técnico'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAM 1º'), (SELECT id FROM asignaturas WHERE nombre='Desarrollo interfaces'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAM 1º'), (SELECT id FROM asignaturas WHERE nombre='Seguridad'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAM 2º'), (SELECT id FROM asignaturas WHERE nombre='Entornos de desarrollo'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAM 2º'), (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAM 2º'), (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAM 2º'), (SELECT id FROM asignaturas WHERE nombre='Desarrollo interfaces'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAM 2º'), (SELECT id FROM asignaturas WHERE nombre='Despliegue de aplicaciones'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAM 2º'), (SELECT id FROM asignaturas WHERE nombre='FOL'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAW 1º'), (SELECT id FROM asignaturas WHERE nombre='Entornos de desarrollo'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAW 1º'), (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAW 1º'), (SELECT id FROM asignaturas WHERE nombre='Inglés Técnico'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAW 1º'), (SELECT id FROM asignaturas WHERE nombre='Seguridad'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAW 1º'), (SELECT id FROM asignaturas WHERE nombre='FOL'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAW 1º'), (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAW 2º'), (SELECT id FROM asignaturas WHERE nombre='Programación'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAW 2º'), (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAW 2º'), (SELECT id FROM asignaturas WHERE nombre='Sistemas Informáticos'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAW 2º'), (SELECT id FROM asignaturas WHERE nombre='Seguridad'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAW 2º'), (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='DAW 2º'), (SELECT id FROM asignaturas WHERE nombre='Bases de datos'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='ASIR 1º'), (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='ASIR 1º'), (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='ASIR 1º'), (SELECT id FROM asignaturas WHERE nombre='FOL'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='ASIR 1º'), (SELECT id FROM asignaturas WHERE nombre='Seguridad'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='ASIR 1º'), (SELECT id FROM asignaturas WHERE nombre='Desarrollo interfaces'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='ASIR 1º'), (SELECT id FROM asignaturas WHERE nombre='Lenguajes de marcas'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='ASIR 2º'), (SELECT id FROM asignaturas WHERE nombre='Bases de datos'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='ASIR 2º'), (SELECT id FROM asignaturas WHERE nombre='Entornos de desarrollo'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='ASIR 2º'), (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='ASIR 2º'), (SELECT id FROM asignaturas WHERE nombre='Desarrollo interfaces'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='ASIR 2º'), (SELECT id FROM asignaturas WHERE nombre='Seguridad'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='ASIR 2º'), (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='SMR 1º'), (SELECT id FROM asignaturas WHERE nombre='FOL'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='SMR 1º'), (SELECT id FROM asignaturas WHERE nombre='Entornos de desarrollo'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='SMR 1º'), (SELECT id FROM asignaturas WHERE nombre='Seguridad'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='SMR 1º'), (SELECT id FROM asignaturas WHERE nombre='Programación'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='SMR 1º'), (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='SMR 1º'), (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='SMR 2º'), (SELECT id FROM asignaturas WHERE nombre='FOL'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='SMR 2º'), (SELECT id FROM asignaturas WHERE nombre='Desarrollo interfaces'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='SMR 2º'), (SELECT id FROM asignaturas WHERE nombre='Bases de datos'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='SMR 2º'), (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='SMR 2º'), (SELECT id FROM asignaturas WHERE nombre='Despliegue de aplicaciones'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='SMR 2º'), (SELECT id FROM asignaturas WHERE nombre='Seguridad'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='IA Básica'), (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='IA Básica'), (SELECT id FROM asignaturas WHERE nombre='Entornos de desarrollo'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='IA Básica'), (SELECT id FROM asignaturas WHERE nombre='Seguridad'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='IA Básica'), (SELECT id FROM asignaturas WHERE nombre='Lenguajes de marcas'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='IA Básica'), (SELECT id FROM asignaturas WHERE nombre='Despliegue de aplicaciones'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='IA Básica'), (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='Full‑stack Web'), (SELECT id FROM asignaturas WHERE nombre='Desarrollo interfaces'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='Full‑stack Web'), (SELECT id FROM asignaturas WHERE nombre='FOL'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='Full‑stack Web'), (SELECT id FROM asignaturas WHERE nombre='Bases de datos'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='Full‑stack Web'), (SELECT id FROM asignaturas WHERE nombre='Despliegue de aplicaciones'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='Full‑stack Web'), (SELECT id FROM asignaturas WHERE nombre='Seguridad'));
INSERT OR IGNORE INTO cursos_asignaturas (curso_id, asignatura_id) VALUES ((SELECT id FROM cursos WHERE nombre='Full‑stack Web'), (SELECT id FROM asignaturas WHERE nombre='Entornos de desarrollo'));
-- Imparticiones
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='alicia.cortés@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'), (SELECT id FROM cursos WHERE nombre='DAM 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='bruno.cortés@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='DAM 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='alicia.cortés@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Lenguajes de marcas'), (SELECT id FROM cursos WHERE nombre='DAM 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='lucía.garrido@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'), (SELECT id FROM cursos WHERE nombre='DAM 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='lucía.cabrera@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Inglés Técnico'), (SELECT id FROM cursos WHERE nombre='DAM 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='alicia.cortés@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Programación'), (SELECT id FROM cursos WHERE nombre='DAM 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='isabel.martín@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Inglés Técnico'), (SELECT id FROM cursos WHERE nombre='DAM 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='óscar.molina@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'), (SELECT id FROM cursos WHERE nombre='DAM 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='alicia.cortés@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Lenguajes de marcas'), (SELECT id FROM cursos WHERE nombre='DAM 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='adrián.guerrero@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Programación'), (SELECT id FROM cursos WHERE nombre='DAM 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='paula.lópez@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Desarrollo interfaces'), (SELECT id FROM cursos WHERE nombre='DAM 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='paula.lópez@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Despliegue de aplicaciones'), (SELECT id FROM cursos WHERE nombre='DAM 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='alberto.ortega@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Programación'), (SELECT id FROM cursos WHERE nombre='DAW 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='iván.pérez@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Sistemas Informáticos'), (SELECT id FROM cursos WHERE nombre='DAW 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='lucía.alonso@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Entornos de desarrollo'), (SELECT id FROM cursos WHERE nombre='DAW 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='adrián.guerrero@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Desarrollo interfaces'), (SELECT id FROM cursos WHERE nombre='DAW 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='alicia.cortés@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'), (SELECT id FROM cursos WHERE nombre='DAW 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='carmen.cano@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Despliegue de aplicaciones'), (SELECT id FROM cursos WHERE nombre='DAW 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='óscar.molina@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'), (SELECT id FROM cursos WHERE nombre='DAW 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='alicia.cortés@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='FOL'), (SELECT id FROM cursos WHERE nombre='DAW 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='lucía.alonso@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Seguridad'), (SELECT id FROM cursos WHERE nombre='DAW 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='alicia.cortés@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Inglés Técnico'), (SELECT id FROM cursos WHERE nombre='DAW 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='óscar.molina@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Despliegue de aplicaciones'), (SELECT id FROM cursos WHERE nombre='DAW 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='óscar.molina@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'), (SELECT id FROM cursos WHERE nombre='DAW 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='alicia.cortés@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Programación'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='lucía.garrido@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Seguridad'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='isabel.martín@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Lenguajes de marcas'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='lucía.alonso@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='carmen.cano@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='alberto.ortega@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='isabel.martín@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Desarrollo interfaces'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='lucía.alonso@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Inglés Técnico'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='carmen.cano@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='elena.ortega@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='paula.lópez@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Seguridad'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='iván.pérez@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Despliegue de aplicaciones'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='lucía.pérez@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Programación'), (SELECT id FROM cursos WHERE nombre='SMR 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='bruno.cortés@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='SMR 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='alberto.ortega@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Inglés Técnico'), (SELECT id FROM cursos WHERE nombre='SMR 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='óscar.molina@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Seguridad'), (SELECT id FROM cursos WHERE nombre='SMR 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='óscar.molina@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'), (SELECT id FROM cursos WHERE nombre='SMR 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='paula.lópez@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Despliegue de aplicaciones'), (SELECT id FROM cursos WHERE nombre='SMR 1º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='elena.ortega@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'), (SELECT id FROM cursos WHERE nombre='SMR 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='óscar.molina@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Sistemas Informáticos'), (SELECT id FROM cursos WHERE nombre='SMR 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='iván.pérez@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Seguridad'), (SELECT id FROM cursos WHERE nombre='SMR 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='lucía.alonso@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Inglés Técnico'), (SELECT id FROM cursos WHERE nombre='SMR 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='paula.lópez@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'), (SELECT id FROM cursos WHERE nombre='SMR 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='bruno.cortés@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Desarrollo interfaces'), (SELECT id FROM cursos WHERE nombre='SMR 2º'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='lucía.pérez@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Lenguajes de marcas'), (SELECT id FROM cursos WHERE nombre='IA Básica'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='elena.ortega@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Despliegue de aplicaciones'), (SELECT id FROM cursos WHERE nombre='IA Básica'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='adrián.guerrero@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='IA Básica'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='lucía.pérez@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Desarrollo interfaces'), (SELECT id FROM cursos WHERE nombre='IA Básica'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='paula.lópez@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Seguridad'), (SELECT id FROM cursos WHERE nombre='IA Básica'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='noa.gómez@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'), (SELECT id FROM cursos WHERE nombre='IA Básica'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='bruno.cortés@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='elena.ortega@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Lenguajes de marcas'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='isabel.martín@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='FOL'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='sara.ruiz@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Desarrollo interfaces'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='lucía.garrido@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Sistemas Informáticos'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'));
INSERT OR IGNORE INTO imparticiones (profesor_id, asignatura_id, curso_id) VALUES ((SELECT id FROM profesores WHERE email='lucía.marín@prof.centro.edu'), (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'));
-- Matrículas
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='juan.medina@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2025-08-08T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='diego.domínguez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 1º'), '2025-02-08T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='iván.díaz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 1º'), '2025-05-09T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='isabel.ruiz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 1º'), '2025-07-21T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='sara.vázquez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-05-19T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='alberto.cabrera@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 2º'), '2024-10-25T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='inés.álvarez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-10-20T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='pablo.cortés@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-01-19T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='sara.guerrero@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2025-03-18T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='sergio.serrano@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2025-04-16T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='pablo.medina@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-02-07T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='rocío.pérez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'), '2025-05-31T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='sara.sánchez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2025-09-27T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='teresa.romero@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 2º'), '2025-07-04T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='clara.méndez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 2º'), '2025-09-16T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='isabel.ortega@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-06-12T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='ariadna.ramos@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2024-09-26T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='raquel.cortés@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2025-06-13T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='raquel.serrano@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2025-03-27T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='daniel.gutiérrez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-04-05T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='ana.cruz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2025-01-28T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='ariadna.gutiérrez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2025-01-10T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='elena.garrido@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2024-11-05T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='daniel.sanz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-09-14T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='clara.gil@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-09-30T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='guillermo.delgado@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2025-03-26T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='irene.castillo@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 2º'), '2025-06-14T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='carlos.ruiz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2024-12-09T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='andrés.suárez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 2º'), '2025-06-18T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='marco.león@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 2º'), '2024-12-22T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='david.díaz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2025-09-25T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='clara.suárez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-08-28T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='juan.prieto@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2025-10-24T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='carlos.león@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-01-19T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='alberto.garrido@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 1º'), '2025-06-14T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='nuria.gil@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'), '2025-08-24T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='álvaro.ramírez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2025-02-02T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='beatriz.rubio@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2025-09-03T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='óscar.flores@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2025-06-17T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='raquel.pérez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2025-07-29T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='elena.torres@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2025-05-23T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='rubén.cruz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-01-31T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='borja.pérez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2025-06-03T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='lucía.gallego@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2025-02-15T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='álvaro.vázquez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2025-06-13T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='nerea.garrido@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-10-20T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='inés.cabrera@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-10-11T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='gonzalo.domínguez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2025-10-20T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='rocío.blanco@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2025-01-20T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='borja.ramírez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2025-02-08T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='maría.castro@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2025-06-26T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='marta.moreno@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2025-09-05T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='teresa.ruiz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 1º'), '2024-11-27T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='clara.sánchez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2025-01-23T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='paula.herrera@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 1º'), '2025-02-12T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='irene.hernández@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2024-11-11T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='lola.gutiérrez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2025-07-04T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='carmen.molina@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-07-20T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='clara.gómez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2025-04-05T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='marco.delgado@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-10-02T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='carmen.medina@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2025-10-22T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='vega.hernández@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 2º'), '2024-12-13T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='laura.medina@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-03-23T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='vega.calvo@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2025-10-01T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='iván.ramírez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 2º'), '2024-11-23T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='inés.blanco@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 1º'), '2025-02-12T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='adrián.díaz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2024-12-27T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='elena.álvarez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2024-11-09T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='julia.alonso@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-10-06T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='borja.alonso@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2025-07-27T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='alex.rubio@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2025-06-14T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='óscar.álvarez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2025-10-28T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='hugo.domínguez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-04-26T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='alex.díaz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-01-22T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='iván.iglesias@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-06-26T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='alicia.santos@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2025-05-24T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='sara.ramos@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2025-04-30T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='diego.cruz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2025-10-29T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='andrés.santos@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-04-17T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='nerea.méndez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 2º'), '2025-02-28T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='lola.sánchez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-02-14T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='raquel.herrera@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2025-06-24T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='inés.flores@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2024-09-27T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='alberto.molina@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2025-09-13T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='carmen.molina@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-09-14T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='carmen.martín@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2025-04-08T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='rubén.guerrero@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'), '2025-10-08T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='carmen.sánchez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 1º'), '2025-10-18T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='sergio.pérez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-05-27T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='paula.delgado@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2025-09-16T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='marco.ruiz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'), '2025-02-01T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='david.castillo@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2024-11-27T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='lucía.martín@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'), '2025-04-13T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='alex.garrido@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2024-10-26T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='julia.iglesias@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2025-08-14T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='pablo.serrano@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2024-10-24T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='teresa.martínez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'), '2024-12-04T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='carlos.romero@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2025-10-07T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='teresa.blanco@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2024-12-12T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='julia.guerrero@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 1º'), '2024-10-19T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='hugo.ramírez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2025-08-19T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='beatriz.serrano@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2024-10-09T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='rubén.ruiz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2025-01-11T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='sofía.rubio@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2024-11-12T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='raquel.ortiz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'), '2024-10-30T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='rubén.vázquez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2025-09-16T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='elena.díaz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2025-10-08T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='pablo.vidal@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2024-12-07T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='david.vidal@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-09-06T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='hugo.ortiz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 1º'), '2025-03-12T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='álvaro.moreno@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2025-10-04T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='nicolás.martínez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2024-12-13T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='paula.sanz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2024-11-15T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='alicia.díaz@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2025-02-21T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='álvaro.iglesias@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-10-28T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='maría.león@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2025-09-24T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='nicolás.vázquez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2025-01-28T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='nerea.gómez@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='DAM 2º'), '2024-11-26T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='álvaro.navarro@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2025-09-26T14:52:45.080089');
INSERT OR IGNORE INTO matriculas (alumno_id, curso_id, fecha) VALUES ((SELECT id FROM alumnos WHERE email='nicolás.serrano@alu.centro.edu'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2025-06-22T14:52:45.080089');
-- Materiales
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 1 - Bases de datos (DAM 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAM_1º/Bases_de_datos/material_1.pdf', (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2025-07-16T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 2 - Bases de datos (DAM 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAM_1º/Bases_de_datos/material_2.pdf', (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2025-07-03T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 3 - Sistemas Informáticos (DAM 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAM_1º/Sistemas_Informáticos/material_3.pdf', (SELECT id FROM asignaturas WHERE nombre='Sistemas Informáticos'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2024-12-01T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 4 - Sistemas Informáticos (DAM 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAM_1º/Sistemas_Informáticos/material_4.pdf', (SELECT id FROM asignaturas WHERE nombre='Sistemas Informáticos'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2025-03-08T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 5 - Entornos de desarrollo (DAM 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAM_1º/Entornos_de_desarrollo/material_5.pdf', (SELECT id FROM asignaturas WHERE nombre='Entornos de desarrollo'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2025-02-19T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 6 - Entornos de desarrollo (DAM 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAM_1º/Entornos_de_desarrollo/material_6.pdf', (SELECT id FROM asignaturas WHERE nombre='Entornos de desarrollo'), (SELECT id FROM cursos WHERE nombre='DAM 1º'), '2025-04-17T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 7 - Bases de datos (DAM 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAM_2º/Bases_de_datos/material_7.pdf', (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='DAM 2º'), '2025-10-06T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 8 - Bases de datos (DAM 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAM_2º/Bases_de_datos/material_8.pdf', (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='DAM 2º'), '2024-12-18T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 9 - Seguridad (DAM 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAM_2º/Seguridad/material_9.pdf', (SELECT id FROM asignaturas WHERE nombre='Seguridad'), (SELECT id FROM cursos WHERE nombre='DAM 2º'), '2024-12-10T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 10 - Seguridad (DAM 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAM_2º/Seguridad/material_10.pdf', (SELECT id FROM asignaturas WHERE nombre='Seguridad'), (SELECT id FROM cursos WHERE nombre='DAM 2º'), '2024-12-04T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 11 - Sistemas Informáticos (DAM 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAM_2º/Sistemas_Informáticos/material_11.pdf', (SELECT id FROM asignaturas WHERE nombre='Sistemas Informáticos'), (SELECT id FROM cursos WHERE nombre='DAM 2º'), '2025-07-20T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 12 - Sistemas Informáticos (DAM 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAM_2º/Sistemas_Informáticos/material_12.pdf', (SELECT id FROM asignaturas WHERE nombre='Sistemas Informáticos'), (SELECT id FROM cursos WHERE nombre='DAM 2º'), '2025-09-20T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 13 - Acceso a datos (DAW 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAW_1º/Acceso_a_datos/material_13.pdf', (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2025-06-21T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 14 - Acceso a datos (DAW 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAW_1º/Acceso_a_datos/material_14.pdf', (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2024-11-30T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 15 - Lenguajes de marcas (DAW 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAW_1º/Lenguajes_de_marcas/material_15.pdf', (SELECT id FROM asignaturas WHERE nombre='Lenguajes de marcas'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2024-11-09T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 16 - Lenguajes de marcas (DAW 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAW_1º/Lenguajes_de_marcas/material_16.pdf', (SELECT id FROM asignaturas WHERE nombre='Lenguajes de marcas'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2025-05-27T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 17 - FOL (DAW 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAW_1º/FOL/material_17.pdf', (SELECT id FROM asignaturas WHERE nombre='FOL'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2024-12-15T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 18 - FOL (DAW 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAW_1º/FOL/material_18.pdf', (SELECT id FROM asignaturas WHERE nombre='FOL'), (SELECT id FROM cursos WHERE nombre='DAW 1º'), '2025-01-12T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 19 - Lenguajes de marcas (DAW 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAW_2º/Lenguajes_de_marcas/material_19.pdf', (SELECT id FROM asignaturas WHERE nombre='Lenguajes de marcas'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2025-09-28T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 20 - Lenguajes de marcas (DAW 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAW_2º/Lenguajes_de_marcas/material_20.pdf', (SELECT id FROM asignaturas WHERE nombre='Lenguajes de marcas'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2025-02-23T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 21 - Programación (DAW 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAW_2º/Programación/material_21.pdf', (SELECT id FROM asignaturas WHERE nombre='Programación'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2025-06-14T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 22 - Programación (DAW 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAW_2º/Programación/material_22.pdf', (SELECT id FROM asignaturas WHERE nombre='Programación'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2024-11-19T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 23 - Seguridad (DAW 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAW_2º/Seguridad/material_23.pdf', (SELECT id FROM asignaturas WHERE nombre='Seguridad'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2025-09-09T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 24 - Seguridad (DAW 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/DAW_2º/Seguridad/material_24.pdf', (SELECT id FROM asignaturas WHERE nombre='Seguridad'), (SELECT id FROM cursos WHERE nombre='DAW 2º'), '2024-11-09T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 25 - Entornos de desarrollo (ASIR 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/ASIR_1º/Entornos_de_desarrollo/material_25.pdf', (SELECT id FROM asignaturas WHERE nombre='Entornos de desarrollo'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-06-03T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 26 - Entornos de desarrollo (ASIR 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/ASIR_1º/Entornos_de_desarrollo/material_26.pdf', (SELECT id FROM asignaturas WHERE nombre='Entornos de desarrollo'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2024-11-01T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 27 - Desarrollo interfaces (ASIR 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/ASIR_1º/Desarrollo_interfaces/material_27.pdf', (SELECT id FROM asignaturas WHERE nombre='Desarrollo interfaces'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-02-07T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 28 - Desarrollo interfaces (ASIR 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/ASIR_1º/Desarrollo_interfaces/material_28.pdf', (SELECT id FROM asignaturas WHERE nombre='Desarrollo interfaces'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-06-05T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 29 - Seguridad (ASIR 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/ASIR_1º/Seguridad/material_29.pdf', (SELECT id FROM asignaturas WHERE nombre='Seguridad'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-03-06T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 30 - Seguridad (ASIR 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/ASIR_1º/Seguridad/material_30.pdf', (SELECT id FROM asignaturas WHERE nombre='Seguridad'), (SELECT id FROM cursos WHERE nombre='ASIR 1º'), '2025-03-05T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 31 - Seguridad (ASIR 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/ASIR_2º/Seguridad/material_31.pdf', (SELECT id FROM asignaturas WHERE nombre='Seguridad'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-07-19T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 32 - Seguridad (ASIR 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/ASIR_2º/Seguridad/material_32.pdf', (SELECT id FROM asignaturas WHERE nombre='Seguridad'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-05-23T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 33 - Bases de datos (ASIR 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/ASIR_2º/Bases_de_datos/material_33.pdf', (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-09-16T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 34 - Bases de datos (ASIR 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/ASIR_2º/Bases_de_datos/material_34.pdf', (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-03-01T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 35 - Inglés Técnico (ASIR 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/ASIR_2º/Inglés_Técnico/material_35.pdf', (SELECT id FROM asignaturas WHERE nombre='Inglés Técnico'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-10-21T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 36 - Inglés Técnico (ASIR 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/ASIR_2º/Inglés_Técnico/material_36.pdf', (SELECT id FROM asignaturas WHERE nombre='Inglés Técnico'), (SELECT id FROM cursos WHERE nombre='ASIR 2º'), '2025-06-03T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 37 - Seguridad (SMR 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/SMR_1º/Seguridad/material_37.pdf', (SELECT id FROM asignaturas WHERE nombre='Seguridad'), (SELECT id FROM cursos WHERE nombre='SMR 1º'), '2025-03-13T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 38 - Seguridad (SMR 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/SMR_1º/Seguridad/material_38.pdf', (SELECT id FROM asignaturas WHERE nombre='Seguridad'), (SELECT id FROM cursos WHERE nombre='SMR 1º'), '2025-06-14T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 39 - Bases de datos (SMR 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/SMR_1º/Bases_de_datos/material_39.pdf', (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='SMR 1º'), '2025-04-14T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 40 - Bases de datos (SMR 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/SMR_1º/Bases_de_datos/material_40.pdf', (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='SMR 1º'), '2025-07-14T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 41 - Inglés Técnico (SMR 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/SMR_1º/Inglés_Técnico/material_41.pdf', (SELECT id FROM asignaturas WHERE nombre='Inglés Técnico'), (SELECT id FROM cursos WHERE nombre='SMR 1º'), '2025-07-14T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 42 - Inglés Técnico (SMR 1º)', 'Recurso de apoyo', 'https://repo.centro.edu/SMR_1º/Inglés_Técnico/material_42.pdf', (SELECT id FROM asignaturas WHERE nombre='Inglés Técnico'), (SELECT id FROM cursos WHERE nombre='SMR 1º'), '2025-09-21T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 43 - Acceso a datos (SMR 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/SMR_2º/Acceso_a_datos/material_43.pdf', (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2025-02-03T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 44 - Acceso a datos (SMR 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/SMR_2º/Acceso_a_datos/material_44.pdf', (SELECT id FROM asignaturas WHERE nombre='Acceso a datos'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2025-06-17T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 45 - Bases de datos (SMR 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/SMR_2º/Bases_de_datos/material_45.pdf', (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2025-04-28T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 46 - Bases de datos (SMR 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/SMR_2º/Bases_de_datos/material_46.pdf', (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2025-08-23T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 47 - Lenguajes de marcas (SMR 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/SMR_2º/Lenguajes_de_marcas/material_47.pdf', (SELECT id FROM asignaturas WHERE nombre='Lenguajes de marcas'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2024-12-25T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 48 - Lenguajes de marcas (SMR 2º)', 'Recurso de apoyo', 'https://repo.centro.edu/SMR_2º/Lenguajes_de_marcas/material_48.pdf', (SELECT id FROM asignaturas WHERE nombre='Lenguajes de marcas'), (SELECT id FROM cursos WHERE nombre='SMR 2º'), '2024-12-10T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 49 - Inglés Técnico (IA Básica)', 'Recurso de apoyo', 'https://repo.centro.edu/IA_Básica/Inglés_Técnico/material_49.pdf', (SELECT id FROM asignaturas WHERE nombre='Inglés Técnico'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2024-11-03T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 50 - Inglés Técnico (IA Básica)', 'Recurso de apoyo', 'https://repo.centro.edu/IA_Básica/Inglés_Técnico/material_50.pdf', (SELECT id FROM asignaturas WHERE nombre='Inglés Técnico'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2025-04-26T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 51 - Sistemas Informáticos (IA Básica)', 'Recurso de apoyo', 'https://repo.centro.edu/IA_Básica/Sistemas_Informáticos/material_51.pdf', (SELECT id FROM asignaturas WHERE nombre='Sistemas Informáticos'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2025-07-03T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 52 - Sistemas Informáticos (IA Básica)', 'Recurso de apoyo', 'https://repo.centro.edu/IA_Básica/Sistemas_Informáticos/material_52.pdf', (SELECT id FROM asignaturas WHERE nombre='Sistemas Informáticos'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2025-02-17T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 53 - Bases de datos (IA Básica)', 'Recurso de apoyo', 'https://repo.centro.edu/IA_Básica/Bases_de_datos/material_53.pdf', (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2025-02-23T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 54 - Bases de datos (IA Básica)', 'Recurso de apoyo', 'https://repo.centro.edu/IA_Básica/Bases_de_datos/material_54.pdf', (SELECT id FROM asignaturas WHERE nombre='Bases de datos'), (SELECT id FROM cursos WHERE nombre='IA Básica'), '2025-04-11T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 55 - Programación (Full‑stack Web)', 'Recurso de apoyo', 'https://repo.centro.edu/Full‑stack_Web/Programación/material_55.pdf', (SELECT id FROM asignaturas WHERE nombre='Programación'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'), '2025-02-20T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 56 - Programación (Full‑stack Web)', 'Recurso de apoyo', 'https://repo.centro.edu/Full‑stack_Web/Programación/material_56.pdf', (SELECT id FROM asignaturas WHERE nombre='Programación'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'), '2024-11-15T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 57 - Lenguajes de marcas (Full‑stack Web)', 'Recurso de apoyo', 'https://repo.centro.edu/Full‑stack_Web/Lenguajes_de_marcas/material_57.pdf', (SELECT id FROM asignaturas WHERE nombre='Lenguajes de marcas'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'), '2025-03-13T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 58 - Lenguajes de marcas (Full‑stack Web)', 'Recurso de apoyo', 'https://repo.centro.edu/Full‑stack_Web/Lenguajes_de_marcas/material_58.pdf', (SELECT id FROM asignaturas WHERE nombre='Lenguajes de marcas'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'), '2025-04-05T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 59 - Empresa e iniciativa (Full‑stack Web)', 'Recurso de apoyo', 'https://repo.centro.edu/Full‑stack_Web/Empresa_e_iniciativa/material_59.pdf', (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'), '2025-05-28T14:52:45.080089');
INSERT INTO materiales (titulo, descripcion, url, asignatura_id, curso_id, creado_en) VALUES ('Material 60 - Empresa e iniciativa (Full‑stack Web)', 'Recurso de apoyo', 'https://repo.centro.edu/Full‑stack_Web/Empresa_e_iniciativa/material_60.pdf', (SELECT id FROM asignaturas WHERE nombre='Empresa e iniciativa'), (SELECT id FROM cursos WHERE nombre='Full‑stack Web'), '2025-08-18T14:52:45.080089');
COMMIT;